name: scanner
description: "Scanner"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^0.8.7
  # tesseract_ocr: ^0.5.0
  google_mlkit_text_recognition: ^0.8.0 # Updated version
  google_mlkit_commons: ^0.4.0 # Updated version
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
