name: scanner
description: "Scanner"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  image_picker: ^0.8.7
  # tesseract_ocr: ^0.5.0
  google_mlkit_text_recognition: ^0.15.0 # Updated version
  google_mlkit_commons: ^0.11.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.2.3
  logging: ^1.2.0
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  uuid: ^4.5.1
  permission_handler: ^12.0.1
  flutter_tts: ^3.8.5
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
